# Generated by Django 4.0.1 on 2022-01-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pdomowa_d2.person')),
                ('genre', models.ManyToManyField(to='pdomowa_d2.Genre')),
                ('screenplay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pdomowa_d2.person')),
                ('starring', models.ManyToManyField(to='pdomowa_d2.Person')),
            ],
        ),
    ]
